name: Okta
highlighter: pygments
exclude: [Gemfile, Gemfile.lock, NOTES.txt, README.md]

markdown: redcarpet 
markdown_ext: md
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


permalink: /blog/:year/:month/:day/:title
