name: Okta
pygments: true
markdown: redcarpet
markdown_ext: md

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# -- blog:NE:NE
permalink: /blog/:year/:month/:day/:title
